### ISSUE TITLE
Bug: First load mat-toolbar styles aren't initialized

### ISSUE THREAD

**Issue by milesmatthias** [alexeagle/angular-bazel-example#271]
`mat-toolbar` children in the nav aren't initialized with mat-toolbar styles. You have to click on one of the nav bars to get the styles applied for some reason.

This is an uncompleted todo from #262.

Note the differences in the following screenshots. The first is page load, the second screenshot is after clicking "Todos" in the nav, and then clicking "Home" in the nav again to return to the home page.

![screen shot 2018-12-13 at 1 41 24 pm](https://user-images.githubusercontent.com/600638/49966332-f61a9e80-fedc-11e8-9f15-009e4f6bdd65.png)
![screen shot 2018-12-13 at 1 41 33 pm](https://user-images.githubusercontent.com/600638/49966333-f6b33500-fedc-11e8-871a-80562512994c.png)

Note: the console errors in those screenshots are all explainable except `system.js` 404ing (`GET http://localhost:5432/system.js net::ERR_ABORTED 404 (Not Found)`), which may be causing this?

**Comment by devversion** [comment]
@milesmatthias @alexeagle I haven't verified locally yet, but at first glance from the screenshots it looks like you just added the `.mat-button` class to the `<a>` element.

This is not how the Angular Material API is intended to be used because the `MatButton/MatAnchor` component is not being instantiated that way.

Therefore the styles for the button aren't really present (only some parts from the theme stylesheet).

**Comment by devversion** [comment]
Can you try actually using the `MatAnchor` selector? e.g.

```html
<a mat-button href="xx">Home</a>
```

**Comment by milesmatthias** [comment]
@devversion yup, that was it. Thanks!
